import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Navbar, NavbarContent, NavbarItem } from "@nextui-org/react";
import Link from "next/link";
import NavigationBar from "@/app/ui/layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="flex flex-col h-lvh">
        <NavigationBar/>
        { children }
      </body>
    </html>
  );
}
